spring:
  application:
    name: wzdf-eureka-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false