spring:
  application:
    name: wzdf-gateway
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    userConsumer:
      service-id: user-consumer
      path: /userconsumer/**
  ignored-services: user-provider
feign.hystrix.enabled: true